name: Continuous Integration

on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Cache NPM & next cache files
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/.next/cache
            ${{ github.workspace }}/.cache
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}-
      - name: Install NPM dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test:ci

  build_nextjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Cache NPM & next cache files
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/.next/cache
            ${{ github.workspace }}/.cache
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}-
      - name: Install NPM dependencies
        run: npm ci
      - name: Build Next.js
        run: npm run build
  
  build_storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Cache NPM & next cache files
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/.next/cache
            ${{ github.workspace }}/.cache
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}-
      - name: Install NPM dependencies
        run: npm ci
      - name: Build Storybook
        run: npm run build-storybook
